name: v1_game
description: Game on Laucher - V1.
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  # Minhas Dependencias =======================================================================
  # Ferramentas ===============================  
  permission_handler: ^11.3.0
  path_provider: ^2.0.13
  xinput_gamepad: ^1.3.1
  provider: ^6.1.2
  change_app_package_name: ^1.1.0  #Renomeia Package do aplicativo completo
  http: ^1.3.0
  html: ^0.15.4
  ffi: ^2.0.1
  win32: ^5.0.0 
  window_manager: ^0.4.3
  # Designer ==================================
  carousel_slider: ^5.0.0
  fluent_ui: ^3.9.1
  bitsdojo_window: ^0.1.6 # Tamanho da tela sem barra superior
  scroll_snap_list: ^0.9.1
  # ===========================================
  # MEDIA =====================================
  process_run: ^0.12.0
  cached_network_image: ^3.3.0  
  url_launcher: ^6.2.6
  # audioplayers: ^6.5.1
  flutter_soloud: ^3.4.7
  flutter_launcher_icons: ^0.14.3
  audio_video_progress_bar: ^2.0.3

  logging: ^1.0.2
  media_kit: ^1.2.6
  media_kit_video: ^1.3.1
  media_kit_libs_video: ^1.0.7
  youtube_explode_dart: ^3.0.5
  path: ^1.9.1
  # Minhas Dependencias =======================================================================

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/IconeAppV1.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:

  uses-material-design: true

  assets:
    # Adicionando Teclado VIrtual ===========
    # - assets/TecladoVirtual/
    # - assets/TecladoVirtual/data/
    # - assets/TecladoVirtual/data/flutter_assets/
    # - assets/TecladoVirtual/data/flutter_assets/fonts/
    # - assets/TecladoVirtual/data/flutter_assets/packages/cupertino_icons/assets/
    # - assets/TecladoVirtual/data/flutter_assets/shaders/
    # Imagens de FUNDO ======================
    - assets/BGdefault.jpeg
    - assets/BGICOdefault.png
    - assets/tutorial.png
    - assets/IconeAppV1.png
    # AUDIOS ================================
    - assets/Sons/SomCheat.mp3
    - assets/Sons/SomCheat2.mp3
    - assets/Sons/SomClick.mp3
    - assets/Sons/SomMovimento.mp3
    - assets/Sons/SomMovimentoBaixo.mp3
    - assets/Sons/Intro.mp3
    # Scripts ===================
    - assets/Scripts/AutoHotkeyA32.exe
    - assets/Scripts/moovMouse.ahk
    # FOTOS CAPA STREAMING ===================
    - assets/StreamingCapa/AppleTv.png
    - assets/StreamingCapa/CrunchyRoll.png
    - assets/StreamingCapa/Disney+.png
    - assets/StreamingCapa/GloboPlay.png
    - assets/StreamingCapa/Max.png
    - assets/StreamingCapa/Netflix.png
    - assets/StreamingCapa/PrimeVideo.png
    - assets/StreamingCapa/TeleCine.png
    - assets/StreamingCapa/Paramount+.png
    - assets/StreamingCapa/Youtube.png
    # FOTOS CAPA STREAMING MUSICAS ===========
    - assets/StreamingCapa/AmazonMusic.png
    - assets/StreamingCapa/spotify.png
    - assets/StreamingCapa/AppleMusic.png
    - assets/StreamingCapa/YoutubeMusic.png
    - assets/StreamingCapa/Deezer.png
    # FOTOS CAPA STREAMING ===================

  #   - images/a_dot_ham.jpeg